### ISSUE TITLE
Error loading Sites

### ISSUE THREAD

**Issue by mattp65** [jamesnovak/Futurez.XrmToolbox.PortalSiteSettings#1]
When loading or refreshing the site list, getting the following error. It loads the grid of settings in the bottom right, but nothing else populates. This is a brand new portal configured based on the Customer Self-Service portal.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Futurez.XrmToolBox.ReflectionHelper.SetSiteSettingsValue(Object target, String propName, String propVal)
   at Futurez.XrmToolBox.OpenIdConnect.LoadItems(EntityCollection entities)
   at Futurez.XrmToolBox.WebSiteSettings.LoadSettings(EntityCollection entities)
   at Futurez.XrmToolBox.PortalSiteSettingsControl.LoadWebSiteSettingObject(Guid websiteId)
   at Futurez.XrmToolBox.PortalSiteSettingsControl.<>c__DisplayClass29_0.<LoadSiteSettings>b__2(RunWorkerCompletedEventArgs e)
   at XrmToolBox.Extensibility.Worker.<>c__DisplayClass4_0.<WorkAsync>b__0(Object s, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

**Comment by mattp65** [comment]
FYI, this is tied to providing the AllowContactMappingWithEmail property on the config. Same error occors with the SAML2 object as with OpenIdConnect.
